# in .cargo/config.toml

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[build]
target = "x86_64-megazord.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]